# Generated by Django 4.1 on 2022-08-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AtbaraApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="Views",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
