# Generated by Django 4.1 on 2022-08-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AtbaraApp", "0002_youtuber_channel_name_youtuber_subscribers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_thumbnail", models.ImageField(upload_to="thumbnail")),
                ("video_title", models.CharField(max_length=255)),
                ("video_desc", models.TextField()),
                ("video", models.FileField(upload_to="videos")),
                (
                    "youtuber_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AtbaraApp.youtuber",
                    ),
                ),
            ],
        ),
    ]
